// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ippimoepciqlmlxigvja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwcGltb2VwY2lxbG1seGlndmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTkzMzYsImV4cCI6MjA2OTg5NTMzNn0.d1xcU9in9VAOh8r4Zbkn8eZYNZnkxriJvwyCijBL7fU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});